name: Deploy Backend to Staging

on:
  push:
    branches:
    - staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: SSH into server & deploy
      uses: appleboy/ssh-action@v1.0.3

      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWORD }}

        script: |
          cd ${{ secrets.SERVER_APP_DIR }}

          echo "Fetching latest code..."
          git fetch --all
          git reset --hard origin/staging

          echo "Installing dependencies..."
          npm install --legacy-peer-deps

          echo "Creating .env from .env.example..."
          cp .env.example .env

          sed -i "s|API_VERSION=.*|API_VERSION=${{ secrets.API_VERSION }}|" .env

          sed -i "s|PORT=.*|PORT=${{ secrets.PORT }}|" .env

          # PostgreSQL
          sed -i "s|DATABASE_URI=.*|DATABASE_URI=${{ secrets.DATABASE_URI }}|" .env

          # SMTP
          sed -i "s|MAIL_MAILER=.*|MAIL_MAILER=smtp|" .env
          sed -i "s|MAIL_HOST=.*|MAIL_HOST=${{ secrets.MAIL_HOST }}|" .env
          sed -i "s|MAIL_PORT=.*|MAIL_PORT=${{ secrets.MAIL_PORT }}|" .env
          sed -i "s|MAIL_USERNAME=.*|MAIL_USERNAME=${{ secrets.MAIL_USERNAME }}|" .env
          sed -i "s|MAIL_PASSWORD=.*|MAIL_PASSWORD=${{ secrets.MAIL_PASSWORD }}|" .env
          sed -i "s|MAIL_ENCRYPTION=.*|MAIL_ENCRYPTION=${{ secrets.MAIL_ENCRYPTION }}|" .env
          sed -i "s|MAIL_FROM_ADDRESS=.*|MAIL_FROM_ADDRESS=${{ secrets.MAIL_FROM_ADDRESS }}|" .env
          sed -i "s|MAIL_FROM_NAME=.*|MAIL_FROM_NAME=\"${{ secrets.MAIL_FROM_NAME }}\"|" .env

          echo "Building TypeScript..."
          npm run build

          echo "Reloading server with zero downtime..."
          pm2 reload backend || pm2 start dist/main.js --name backend
